#!/bin/zsh
startx() command startx "$XINITRC" -- "$XSERVERRC" &>"$XLOG"
alias \
	lp='spawn leafpad' \
	gp='spawn gpicview' \
	gn='spawn geany' \
	fr='spawn file-roller' \
	kr='spawn krita' \
	za='spawn zathura' \
