user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("privacy.resistFingerprinting.letterboxing", true);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"stop-reload-button\",\"forward-button\",\"urlbar-container\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[],\"dirtyAreaCache\":[],\"currentVersion\":18}");
user_pref("browser.download.dir", "/home/cationiz3r/downloads");
user_pref("browser.download.useDownloadDir", true);
user_pref("general.autoScroll", true);
user_pref("general.smoothScroll", false);
user_pref("keyword.enabled", true);
user_pref("font.name.sans-serif.x-western", "Poppins");
user_pref("font.name.serif.x-western", "Poppins");
user_pref("font.name.monospace.x-western", "JetBrains Mono");
