#!/bin/sh
xset m 20/10 10 r rate 300 30 b on &
xhost +si:localuser:$USER &

killall dunst; dunst &
dunstctl rule lockscreen disable &
ibus-daemon -drx &
overcharge &
picom &
redshift &
$XDG_CONFIG_HOME/polybar/launch &
chkboot &
forgetful -g &
mpd-notify &
numlockx &
waldate &

mkdir -p "$XDG_RUNTIME_DIR/thumbnails" &
mkdir -p "$XDG_RUNTIME_DIR/tordownload" &

exec openbox
