#!/bin/sh
xset m 20/10 10 r rate 300 30 b on &
xhost +si:localuser:$USER &

$XDG_CONFIG_HOME/dunst/launch &
ibus-daemon -drx &
overcharge &
picom --config "$PICOM_CONF" &
redshift &
$XDG_CONFIG_HOME/polybar/launch &
forgetful -g &
mpd-notify &
numlockx &
waldate &
xborders --config "$XDG_CONFIG_HOME/xborders/config.json" &

for d in thumbnails tordownload; do
	mkdir -p "$XDG_RUNTIME_DIR/$d" &
done
rm -rf "$XDG_CACHE_HOME/thumbnails"
ln -s "$XDG_RUNTIME_DIR/thumbnails" "$XDG_CACHE_HOME"

exec i3 -V
