"" Source system files
function! SourceExists(file)
	if filereadable(expand(a:file))
		exe 'source' a:file
	endif
endfunction

call SourceExists("/usr/share/vim/vimfiles/archlinux.vim")
call SourceExists("$VIMRUNTIME/vimrc_example.vim")

"" Key binding
" Normal
nmap <c-r> :so ~/.config/vim/vimrc<CR>
nmap <c-q> :x<CR>
nmap <c-d> :q!<CR>
nmap <c-s> :up<CR>
nmap <s-Up> v<Up>
nmap <s-Down> v<Down>
nmap <s-Left> v<Left>
nmap <s-Right> v<Right>
nmap <c-z> :undo<Cr>
nmap <c-y> :redo<Cr>
nmap <c-v> p
nmap <End> <End><Right>
" Visual
vmap <c-r> <Esc>:so ~/.config/vim/vimrc<CR>
vmap <c-q> <Esc>:x<CR>
vmap <c-d> <Esc>:q!<CR>
vmap <c-s> <Esc>:up<CR>
vmap <s-Up> <Up>
vmap <s-Down> <Down>
vmap <s-Left> <Left>
vmap <s-Right> <Right>
vmap <c-c> y
vmap <c-x> x
vmap <c-v> p
" Insert
imap <s-Up> <Esc>v<Up>
imap <s-Down> <Esc>v<Down>
imap <s-Left> <Esc>v<Left>
imap <s-Right> <Esc>v<Right>

"" General
filetype plugin on
syntax on
colorscheme pablo
set t_Co=16
set tabstop=2
set shiftwidth=2
set number
set viminfo=
set autoindent
set smartindent
set scrolloff=5
let g:python_recommended_style = 0

set nobackup
set ignorecase
silent
set virtualedit=onemore

" Powerline-esque Status line
set noshowmode
set laststatus=2

function! UpdateStatus(id)
	set statusline=%1*\ 
	if (mode() =~# '\v(n|no)')
		set statusline+=NORMAL
  elseif (mode() =~# '\v(v|V)')
		set statusline+=VISUAL
  elseif (mode() ==# 'i')
		set statusline+=INSERT
  elseif (mode() ==# 'R')
		set statusline+=REPLACE
  else
		set statusline+=COMMAND
		echo mode()
  endif
  set statusline+=\ %*\ %<%f%m\ %=%1*\ %c%V\ \ %l\ %2*%*%1*\ %P\ 
endfunction
call timer_start(100, function('UpdateStatus'), {'repeat': -1})

"" Highlight
set cursorline
hi Normal       guibg=NONE ctermbg=NONE
hi LineNr       cterm=bold ctermbg=0   ctermfg=12
hi CursorLine   cterm=bold ctermbg=0
hi CursorLineNr cterm=bold ctermbg=9   ctermfg=15
hi StatusLine   cterm=bold ctermbg=233 ctermfg=15
hi StatusLineNc cterm=bold ctermbg=233 ctermfg=15
hi User1        cterm=bold ctermbg=15  ctermfg=0
hi User2        cterm=bold ctermbg=15  ctermfg=233
if $TERM == 'linux-16color'
	hi StatusLine   cterm=bold ctermbg=0  ctermfg=15
	hi StatusLineNc cterm=bold ctermbg=0  ctermfg=15
	hi User2        cterm=bold ctermbg=15 ctermfg=0
endif


" Command line text
"augroup cmdlinemsg
"	let g:cmdmsg="Awaiting disasters to happen..."
"	autocmd!
"	au CursorMoved  * :echo g:cmdmsg
"	au CursorHold   * :echo g:cmdmsg
"	au TextChanged  * :echo g:cmdmsg
"	au TextChangedI * :echo g:cmdmsg
"augroup END
