#!/bin/sh
# Use only for deluge

pgrep deluged >/dev/null || { echo; exit; }

## Get torrent count
#IFS=: read down seed <<EOF
#$(deluge-console status 2>/dev/null|grep 'Down\|Seed'|cut -d\  -f3|tr \\n :)
#EOF

# Get ratio
info=$(timeout 10 deluge-console info --detailed 2>/dev/null)
[ -z "$info" ] && { echo; exit; }
sumof() {
	echo "$info"|\
		grep -oP "(?<=$1:)( [^ /]+){2}+"|\
		tr -d \ |\
		grep -Ev '^0B$'|\
		numfmt --from=iec|\
		awk 'BEGIN{sum=0} {sum=sum+$1} END{printf "%.0f\n", sum}'
}
ratio=$(echo "scale=4; $(sumof Uploaded)*100/$(sumof Size)"|bc)
echo $ratio|cut -b-4|grep -q '\.' &&
	ratio=$(echo "$ratio"|cut -b-4|sed 's/\.$//') ||
	ratio=$(echo "$ratio"|cut -d. -f1)

echo " $ratio"
