#!/bin/sh
out() { echo " $@  %{B$BACKGROUND F$BACKGROUND}|%{B$BACKGROUND_ALT F-}  "; }
waitonline() {
	out ..\?
	for i in $(seq 1 30); do
		ping -c1 archlinux.org >/dev/null 2>&1 && break; sleep 2
	done
}
cache="$POLYBAR_RUN/updates"
force() { ps -p $sleep_pid >/dev/null && kill $sleep_pid; }
trap 'force; exit' INT
trap force USR1 USR2 EXIT
while true; do
	waitonline; out ...
	[ -f "$cache" ] || checkupdates 2>&1 >"$cache"
	[ -f "$cache.pw" ] || which pkgwatch >/dev/null 2>&1 && pkgwatch >"$cache.pw"
	(
		PKGS=$(cat "$cache"|wc -l)
		PKGS_EX=$(cat "$cache.pw"|wc -l)
		TOT=$((PKGS + PKGS_EX))
		[ $TOT -eq 0 ] && { echo; exit; }
		[ $PKGS -eq 1 ] && [ "$(cat "$cache")" = '==>' ] &&
			{ out '%{T2}?'; exit; }
		[ $PKGS_EX -gt 0 ] && TOT="$TOT ($PKGS_EX)"
		out "$TOT"
	)
	sleep 30m & sleep_pid=$!
	wait
	rm -f "$cache" "$cache.pw"
done
