require("core.plugin_config.lualine")
require("core.plugin_config.tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.bufferline")
require("core.plugin_config.dracula")
require("core.plugin_config.comment")
require("core.plugin_config.gitsigns")
