#!/bin/sh

prepend_info() {
	local date=$(date --iso-8601=seconds)
	local task="$@"
	local line
	while read line; do
		echo "[$date][$task] $line"
	done
}

{ "$@" 2>&3|prepend_info "$1"; } 3>&1 1>&2|prepend_info "$1/err"
