#!/bin/sh

while [ $# -ne 0 ]; do
	# Get relative path to music dir
	select="$(realpath "$1"|sed -E "s:.*music/::")"
	mpc add "$select"

	shift
done

# Play last item
mpc play -q $(mpc playlist|wc -l)
