#!/bin/sh
[ -z "$(acpi -b 2>/dev/null)" ] && exit

notify() { dunstify -h string:x-dunst-stack-tag:overcharge -u critical -t 65000 "$@"; }

get_state()  { acpi -a|grep -q 'on-line'; }
get_charge() { acpi -b|grep -Eo '[0-9]+%'|head -c-2; }
get_conf() {
	conf_low=40
	conf_critlow=10
	conf_high=80

	local conf_file="$XDG_CONFIG_HOME/_custom/overcharge.conf"
	[ -r "$conf_file" ] && . "$conf_file"
}

get_conf
while true; do
	power_level=$(get_charge)
	if ! get_state && [ $power_level -le $conf_low ]; then
		notify 'Low'
	elif get_state && [ $power_level -ge $conf_high ]; then
		notify 'Full'
	fi
	sleep 1m
done
