#!/bin/sh

# Get numbers of songs in current playlist
get_playlist_length() {
	mpc playlist|wc -l
}
before_add=$(get_playlist_length)

# Go into music folder
. "$XDG_CONFIG_HOME/user-dirs.dirs"
cd "$XDG_MUSIC_DIR"

# Ignore control & SFX dirs
select=$(
	find -mindepth 1|\
	cut -b3-|\
	grep -vE '^_'|\
	sort|\
	rofi -theme list -dmenu
)

# Quit if empty
[ -z "$select" ] && exit

# Add to current playlist
mpc add "$select"

# Play random item from new items
after_add=$(get_playlist_length)
[ $before_add -eq $after_add ] && exit
item=$(seq $((before_add + 1)) $after_add|shuf -n1)
echo $before_add $after_add $item
mpc play -q "$item"
