#!/bin/sh

# Go into music folder
. "$XDG_CONFIG_HOME/user-dirs.dirs"
cd "$XDG_MUSIC_DIR"

# Ignore control & SFX dirs
select=$(
	find -mindepth 1|\
	cut -b3-|\
	grep -vE '^_'|\
	sort|\
	rofi -theme list -dmenu
)

# Quit if empty
[ -z "$select" ] && exit

# Add to current playlist
mpc add "$select"

# Play last item in play list
mpc play -q "$(mpc playlist|wc -l)"
