#!/bin/sh
root="$XDG_CONFIG_HOME/_custom/waldate"
# night---[1]-----day-----[2]---night
day_begin=21600 #6:00
day_end=68400 #19:00
[ -r "$root/config" ] && . "$root/config"
while true; do
	time=$(( ($(date +%s) + $(date +%z|head -c+3|sed -E 's/^(.)0/\1/')*3600) % 86400 ))
	wal=night
	[ $time -ge $day_begin ] && [ $time -lt $day_end ] && wal=day
	echo waldate: $time $wal
	echo waldate: setting to $(realpath "$root/$wal")
	[ "$last" = $wal ] || xwallpaper --zoom "$root/$wal"
	last=$wal
	sleep 5m
done
