#!/bin/sh

set_wallpaper() {
	xwallpaper --zoom "$1"
}

# Compare current time to day range
is_day() {
	local now=$(date '+%H:%M')

	# Check if in range
	[ ! "$now" \< "$day_begin" ] && [ "$now" \< "$day_end" ]
	return $?
}

# Source config file
. "$XDG_CONFIG_HOME/_custom/waldate.conf"

# Main
wal="$night_wallpapers"
if [ $# -gt 0 ]; then
	# ignore check if args
	[ "$1" = "day" ] && wal="$day_wallpapers"
elif is_day; then
	wal="$day_wallpapers"
fi

# Expand if target is a directory
if [ -d "$wal" ]; then
	wal=$(find "$wal" -type f|shuf -n1)
fi

set_wallpaper "$wal"
