#!/bin/sh

set_wallpaper() {
	root="$XDG_CONFIG_HOME/_custom/waldate"
	echo "waldate: $1"
	xwallpaper --zoom "$root/$1"
}

is_day() {
	local day_begin=06:00
	local day_end=19:00
	local now=$(date '+%H:%M')

	# Check if in range
	[ ! "$now" \< "$day_begin" ] && [ "$now" \< "$day_end" ]
	return $?
}

# parse args
wal=night
if [ $# -gt 0 ]; then
	# ignore check if args
	[ "$1" = "day" ] && wal=day
elif is_day; then
	wal=day
fi

set_wallpaper "$wal"
