#!/bin/sh
cd "$(dirname "$0")"
pgrep polybar && killall polybar

# Wait for window manager, fixes empty xworkspace module
while ! pgrep i3 >/dev/null; do
	sleep 1
done
sleep 1 # give wm headstart

export \
	POLYBAR_ROOT=$(pwd) \
	POLYBAR_RUN="$XDG_RUNTIME_DIR/polybar" \
	BACKGROUND=$(grep background\          colors.ini|head -1|cut -d\  -f3) \
	BACKGROUND_ALT=$(grep background-alt\  colors.ini|head -1|cut -d\  -f3)
mkdir -vp "$POLYBAR_RUN"
export SEP="    %{B$BACKGROUND F$BACKGROUND}  %{B$BACKGROUND_ALT F-}    "
exec polybar
