#!/bin/sh
cd "$(dirname "$0")"
killall -q polybar

# Wait for i3 to start and create socket
while ! pgrep i3 >/dev/null; do
	sleep 1
done
i3_pid=$(pgrep i3)
while ! [ -S "$XDG_RUNTIME_DIR/i3/ipc-socket.$i3_pid" ]; do
	sleep 1
done

export \
	POLYBAR_ROOT=$(pwd) \
	POLYBAR_RUN="$XDG_RUNTIME_DIR/polybar" \
	BACKGROUND=$(grep background\          colors.ini|head -1|cut -d\  -f3) \
	BACKGROUND_ALT=$(grep background-alt\  colors.ini|head -1|cut -d\  -f3)
mkdir -vp "$POLYBAR_RUN"
export SEP="    %{B$BACKGROUND F$BACKGROUND}  %{B$BACKGROUND_ALT F-}    "
exec polybar
