require("core.plugins.editor.bufferline")
require("core.plugins.editor.colorscheme")
require("core.plugins.editor.comment")
require("core.plugins.editor.gitsigns")
require("core.plugins.editor.lualine")
require("core.plugins.editor.syntax")
require("core.plugins.editor.tree")
